### ISSUE TITLE
cycleblob.com offline?

### ISSUE THREAD

**Issue by greggles** [shooshx/CycleBlob#1]
currently it's giving a 404:

```
404

There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.
```

**Comment by shooshx** [comment]
thanks for reporting, I'm switching from my old hosting to github pages so the domain name cycleblob.com is still not updated property. this will be fixed soon I hope. In the mean time the game is available in http://shooshx.github.io/CycleBlob/

**Comment by shooshx** [comment]
cycleblob.com is fixed now :)

**Comment by greggles** [comment]
You're the best. Thanks.
